services:
  db:
    image: postgres:16-alpine
    container_name: subtrackr_db
    environment:
      POSTGRES_USER: "sbtrckr_user"
      POSTGRES_PASSWORD: "sbtrckr_pass"
      POSTGRES_DB: "subtrackr_db"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: