spring:
  application:
    name: subtrackr
  datasource:
    url: jdbc:postgresql://localhost:5432/subtrackr_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
  web:
    error:
      include-stacktrace: never

server:
  port: ${PORT:8080}

logging:
  level:
    com.aggxb.subtrackr: debug